sudo: require
services:
  - docker

before_install:
  - docker build -t claragaillard59/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true claragaillard59/react-test npm test

after_success:
  - docker build -t claragaillard59/multi-client ./client
  - docker build -t claragaillard59/multi-nginx ./nginx
  - docker build -t claragaillard59/multi-server ./server
  - docker build -t claragaillard59/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to the docker hub
  - docker push claragaillard59/multi-client
  - docker push claragaillard59/multi-nginx
  - docker push claragaillard59/multi-server
  - docker push claragaillard59/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-051866226801
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY